test:
	g++ -c *.cpp -I ./
	g++ *.o

# before F() macro
# Sketch uses 1374785 bytes (69%) of program storage space. Maximum is 1966080 bytes.
# Global variables use 68108 bytes (20%) of dynamic memory, leaving 259572 bytes for local variables. Maximum is 327680 bytes.
# After F() macro
# ketch uses 1374785 bytes (69%) of program storage space. Maximum is 1966080 bytes.
#Global variables use 68108 bytes (20%) of dynamic memory, leaving 259572 bytes for local variables. Maximum is 327680 bytes.

#ketch uses 1381917 bytes (70%) of program storage space. Maximum is 1966080 bytes.
#Global variables use 68108 bytes (20%) of dynamic memory, leaving 259572 bytes for local variables. Maximum is 327680 bytes.
# Turning off the printouts.. MACROS do work..
#ketch uses 1355053 bytes (68%) of program storage space. Maximum is 1966080 bytes.
#Global variables use 68100 bytes (20%) of dynamic memory, leaving 259580 bytes for local variables. Maximum is 327680 bytes
